"""create post favorites table

Revision ID: 2ba82f5e5efe
Revises: 4a42b0980129
Create Date: 2026-09-01 16:48:49.145383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ba82f5e5efe'
down_revision = '4a42b0980129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_favorites',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name='uq_post_favorites_user_post')
    )
    with op.batch_alter_table('post_favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_favorites_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_favorites_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_favorites_user_id'))
        batch_op.drop_index(batch_op.f('ix_post_favorites_post_id'))

    op.drop_table('post_favorites')
    # ### end Alembic commands ###
